name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  neutral:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: BricolageGrotesque
      fonts:
      - asset: ./fonts/static/BricolageGrotesque-ExtraLight.ttf
        weight: 200
      - asset: ./fonts/static/BricolageGrotesque-Light.ttf
        weight: 300
      - asset: ./fonts/static/BricolageGrotesque-Regular.ttf
        weight: 400
      - asset: ./fonts/static/BricolageGrotesque-Medium.ttf
        weight: 500
      - asset: ./fonts/static/BricolageGrotesque-SemiBold.ttf
        weight: 600
      - asset: ./fonts/static/BricolageGrotesque-Bold.ttf
        weight: 700
      - asset: ./fonts/static/BricolageGrotesque-ExtraBold.ttf
        weight: 800